### PR TITLE
Simplify often-used ident/punct parsers

### PR DESCRIPTION
**Pull request by Bromeon**
Builds on top of #33, which should be merged first

Relevant diff: [here](https://github.com/PoignardAzur/venial/pull/34/files/8f3644da954bebee5405bda1713b945299795b7f..7393f4f38b8ff674901c01a78e775c3569b3464c)
~~Relevant diff: [`c4499e9..397ed81`](https://github.com/PoignardAzur/venial/pull/34/files/c4499e98e7b683e451b3a14e945ffd5591a9826e..397ed8114086b2fe1412824f6c5d37c7b59e8600)~~

### CODE REVIEW

**Comment by PoignardAzur** [comment]
LGTM.

**Comment by PoignardAzur** [comment]
Longer review: this seems like a straight improvement that makes the code easier to read. The patch respects the naming scheme we discussed, which I definitely appreciate.

This is good to merge as soon as #33 is merged.

**Comment by Bromeon** [comment]
Rebased.

**Comment by PoignardAzur** [comment]
Feel free to merge this as soon as you've fixed merge conflicts.

**Pull request merged**
